sonar.projectKey=To-Do-List-Equipo-8
sonar.projectName=To-Do List Equipo 8
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=src,App.js,selenium_tests/pages
sonar.tests=src/api/__tests__,selenium_tests/tests

sonar.exclusions=\
node_modules/**,\
.expo/**,\
dist/**,\
coverage/**,\
reports/**,\
assets/**

sonar.test.inclusions=\
src/api/__tests__/**/*.test.js,\
selenium_tests/tests/**/*.py

sonar.coverage.exclusions=\
src/**/__tests__/**,\
**/*.test.js,\
selenium_tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.version=3.11
